language: python
python:
- '3.6'
services:
- docker
env:
  global:
  - SERVICE_UUID=70a5867c-5ae1-404a-bd5e-9bf23adc9eb4
  - AOS_UPLOAD_SERVICE_URL=https://aoscloud.io:10000/api/v1/services/versions/
  - SP_CERTIFICATE=meta_folder/sp-client.pem
  - PRIVATE_KEY=meta_folder/private_key.pem
install:
- pip install docker-compose
- sudo apt-get install curl
- mkdir package
script:
- docker pull aoscloud/aos_signer:1.0.0
- docker run -v $(pwd)/meta_folder:/data/meta/ -v $(pwd)/src/:/data/src/ -v $(pwd)/package:/data/package
  aoscloud/aos_signer:1.0.0
- curl --request POST -k -v --cacert meta_folder/rootCA.crt.pem --cert $SP_CERTIFICATE
  --key $PRIVATE_KEY --form "service=$SERVICE_UUID" --form "file=@package/service.tar.gz"
  $AOS_UPLOAD_SERVICE_URL
dd:
- openssl aes-256-cbc -K $encrypted_5456e82ea340_key -iv $encrypted_5456e82ea340_iv
  -in meta_folder/private_key.pem.enc -out meta_folder/private_key.pem.enc  -d
